<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5d9dbcc5-6d92-4bc5-af09-295d646b7404</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.19" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.19" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.19">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ExpenseSplitter.Application\ExpenseSplitter.Application.csproj" />
	  <ProjectReference Include="..\ExpenseSplitter.Domain\ExpenseSplitter.Domain.csproj" />
	  <ProjectReference Include="..\ExpenseSplitter.Infrastructure\ExpenseSplitter.Infrastructure.csproj" />
	</ItemGroup>

</Project>
